apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app
  labels:
    app: gcp-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
        - name: gcp-devops-app
          image: pioti2252/gcp-devops-showcase:1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gcp-devops-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20