apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-service
  labels:
    app: gcp-devops-app
spec:
  type: LoadBalancer
  selector:
    app: gcp-devops-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080